In [6]:
import yfinance as yf

In [7]:
# download the stock data corresponding to PFE
pfe_stock_data = yf.download('PFE', start='2020-12-12', end='2021-11-23', progress=False)

In [8]:
pfe_stock_data.head()

                 Open       High        Low      Close  Adj Close    Volume
Date
2020-12-14  41.619999  41.660000  39.070000  39.209999  37.448860  94809700
2020-12-15  39.060001  39.180000  38.209999  38.709999  36.971317  65712800
2020-12-16  38.180000  38.470001  37.740002  37.840000  36.140400  56515300
2020-12-17  37.830002  38.119999  37.310001  38.029999  36.321865  52036400
2020-12-18  37.990002  38.090000  37.500000  37.680000  35.987579  60259200

In [9]:
pfe_stock_data.head()

                 Open       High        Low      Close  Adj Close    Volume
Date
2020-12-14  41.619999  41.660000  39.070000  39.209999  37.448860  94809700
2020-12-15  39.060001  39.180000  38.209999  38.709999  36.971317  65712800
2020-12-16  38.180000  38.470001  37.740002  37.840000  36.140400  56515300
2020-12-17  37.830002  38.119999  37.310001  38.029999  36.321865  52036400
2020-12-18  37.990002  38.090000  37.500000  37.680000  35.987579  60259200

In [10]:
# Save the PFE stock data to file
pfe_stock_data.to_csv(r'csv/pfe_stock_data.csv', encoding = 'utf-8')